INSERT INTO users (id, first_name, last_name, address1, address2, city, postcode)
VALUES 
    (1, 'John', 'Doe', '123 Main St', 'Flat 1', 'Anytown', 'AB1 2CD'),
    (2, 'Jane', 'Smith', '456 Oak Ave', 'Apt 3B', 'Otherville', 'EF3 4GH'),
    (3, 'Bob', 'Johnson', '789 Elm St', 'Unit 10', 'Cityville', 'IJ5 6KL'),
    (4, 'Emily', 'Williams', '345 Pine Rd', 'Suite B', 'Smalltown', 'MN7 8OP'),
    (5, 'Michael', 'Jones', '10 Downing St', 'Adubung', 'London', 'SW1A 2AA'),
    (6, 'Amy', 'Brown', '25 Park St', 'Apt 2C', 'Birmingham', 'B2 4EG'),
    (7, 'Peter', 'Davis', '17 Bridge Rd', 'addoru', 'Manchester', 'M1 3BE'),
    (8, 'Sarah', 'Taylor', '23 High St', 'Flat 5', 'Glasgow', 'G1 1XQ'),
    (9, 'David', 'Clark', '39 Church Rd', 'Suite 12', 'Bristol', 'BS1 5TB'),
    (10, 'Emma', 'Roberts', '7 Albert Square', 'Lama', 'Liverpool', 'L1 1RJ'),
    (11, 'Richard', 'Walker', '18 York St', 'Unit 3A', 'Leeds', 'LS1 2ED'),
    (12, 'Sophie', 'Wilson', '2 Queen St', 'Apt 8', 'Newcastle', 'NE1 3UG'),
    (13, 'Tom', 'Jackson', '15 Broadway', 'Samba', 'Brighton', 'BN1 4AL'),
    (14, 'Olivia', 'Wright', '9 Victoria Rd', 'Suite C', 'Southampton', 'SO1 1ZP'),
    (15, 'Christopher', 'Green', '12 Union St', 'Flat 4B', 'Sheffield', 'S1 2JR'),
    (16, 'Laura', 'Hall', '21 Market St', 'Unit 9', 'Nottingham', 'NG1 3AA'),
    (17, 'Matthew', 'Harris', '3 High St', 'Apt 6D', 'Cardiff', 'CF1 1AA'),
    (18, 'Anna', 'Martin', '8 Park Rd', 'Suite 2B', 'Belfast', 'BT1 1AA'),
    (19, 'Mark', 'Lee', '4 Station Rd', 'Aarosona', 'Edinburgh', 'EH1 1AA'),
    (20, 'Lucy', 'Anderson', '27 Queen St', 'Flat 3', 'Dundee', 'DD1 1AA');