server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://postgres:5432/okayreet
    username: "okayreet"
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
